### ISSUE TITLE
Use image data as the icon for pixmap clipboard data

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pvanek/qlipper-googlecode-backup#10]
```
Attached is a small patch that allows image data to be distinguished from other 
binary data types by using the image as the menu icon.
```

Original issue reported on code.google.com by `shadowky...@gmail.com` on 21 Feb 2012 at 1:28

Attachments:
* [image_as_clipicon_qlipper.patch](https://storage.googleapis.com/google-code-attachments/qlipper/issue-10/comment-0/image_as_clipicon_qlipper.patch)

**Comment by pvanek** [comment]
This issue was moved to pvanek/qlipper#8
